### ISSUE TITLE
Urgent - can you pls send the QR code for the expo?

### ISSUE THREAD

**Issue by liaz-af** [amnon3234/FoodByMood#1]
I can't install anything locally on my machine

Good luck

**Comment by amnon3234** [comment]
Hi, when you run expo start, new web browser will appear with the qr code.
like in the example below:
[image: image.png]

[image: image.png]
[image: image.png]

the qr will appear in the left bottom corner and will be unique to your
computer and your lan, I recommend to press on tunnel connection because
the lan can make some troubles.

If it is still not working i am available at 054-7443846 and here by mail
and I think I can open you a tunnel connection from here but it will be
slower.

Thank You, Amnon

**Comment by amnon3234** [comment]
hey, I just publish the app to expo : you can review it in this link here
https://expo.io/@amnon3234/projects/FoodByMood

however i notice that one bug appears on publish when you checkout your
order the app crashes so you may expat that in the publish version.
It will work in the github version

**Comment by amnon3234** [comment]
please verify that everything is working 😊 and again thank you

**Comment by liaz-af** [comment]
Works well enough.
I did got an error when logging with the credentials you published.
But I managed to register, which is fine.

Good luck
